version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: example_user
      RABBITMQ_DEFAULT_PASS: example_password
      RABBITMQ_VHOST: example_vhost
      
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      DB_URL: "postgresql+asyncpg://example_user:example_password@postgres:5432/example_db"
      RABBITMQ_URL: "amqp://example_user:example_password@rabbitmq:5672/example_vhost"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./logs:/app/logs 

volumes:
  postgres_data:
  postgres_test_data:
